/**
 * Export snarkjs verification key to groth16-solana Rust format.
 *
 * Converts verification_key.json (from snarkjs zkey export verificationkey)
 * into a Rust source file with the Groth16Verifyingkey struct.
 *
 * Usage: node export_vk_solana.mjs
 * Output: ../programs/vusd-vault/src/keys/verifying_key.rs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const inputArg = process.argv[2];
const writeArg = process.argv[3];
const vkPath = inputArg
    ? path.resolve(process.cwd(), inputArg)
    : path.join(__dirname, "build", "verification_key.json");

function bigIntToBeBytes32(bi) {
    const hex = BigInt(bi).toString(16).padStart(64, "0");
    const bytes = [];
    for (let i = 0; i < 64; i += 2) {
        bytes.push(parseInt(hex.substr(i, 2), 16));
    }
    return bytes;
}

function g1ToBytes(point) {
    // G1 point: [x, y] -> 64 bytes big-endian
    const x = bigIntToBeBytes32(point[0]);
    const y = bigIntToBeBytes32(point[1]);
    return [...x, ...y];
}

function g2ToBytes(point) {
    // G2 point: [[x0, x1], [y0, y1]] -> 128 bytes big-endian
    // groth16-solana expects: x1, x0, y1, y0 (reversed within each coordinate pair)
    const x0 = bigIntToBeBytes32(point[0][0]);
    const x1 = bigIntToBeBytes32(point[0][1]);
    const y0 = bigIntToBeBytes32(point[1][0]);
    const y1 = bigIntToBeBytes32(point[1][1]);
    return [...x1, ...x0, ...y1, ...y0];
}

function formatByteArray(bytes, indent = "    ") {
    const lines = [];
    for (let i = 0; i < bytes.length; i += 16) {
        const chunk = bytes.slice(i, i + 16);
        lines.push(indent + chunk.map(b => b.toString()).join(", ") + ",");
    }
    return lines.join("\n");
}

function buildRustSource(vk) {
    const alphaG1 = g1ToBytes(vk.vk_alpha_1);
    const betaG2 = g2ToBytes(vk.vk_beta_2);
    const gammaG2 = g2ToBytes(vk.vk_gamma_2);
    const deltaG2 = g2ToBytes(vk.vk_delta_2);

    const icPoints = vk.IC.map(p => g1ToBytes(p));
    const nrPubInputs = icPoints.length - 1;

    let rust = `// Auto-generated by export_vk_solana.mjs — do not edit
// Verifying key for the VaultProof compliance circuit
// Public inputs: ${nrPubInputs}

use groth16_solana::groth16::Groth16Verifyingkey;

pub const NR_PUBLIC_INPUTS: usize = ${nrPubInputs};

pub const VK_ALPHA_G1: [u8; 64] = [
${formatByteArray(alphaG1)}
];

pub const VK_BETA_G2: [u8; 128] = [
${formatByteArray(betaG2)}
];

pub const VK_GAMMA_G2: [u8; 128] = [
${formatByteArray(gammaG2)}
];

pub const VK_DELTA_G2: [u8; 128] = [
${formatByteArray(deltaG2)}
];

pub const VK_IC: [[u8; 64]; ${icPoints.length}] = [
`;

    for (let i = 0; i < icPoints.length; i++) {
        rust += `    // IC[${i}]\n`;
        rust += `    [\n${formatByteArray(icPoints[i], "        ")}\n    ],\n`;
    }

    rust += `];

pub fn get_verifying_key() -> Groth16Verifyingkey<'static> {
    Groth16Verifyingkey {
        nr_pubinputs: NR_PUBLIC_INPUTS,
        vk_alpha_g1: VK_ALPHA_G1,
        vk_beta_g2: VK_BETA_G2,
        vk_gamme_g2: VK_GAMMA_G2, // Note: typo is in the groth16-solana API
        vk_delta_g2: VK_DELTA_G2,
        vk_ic: &VK_IC,
    }
}
`;

    return rust;
}

function main() {
    const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));
    const rust = buildRustSource(vk);

    if (writeArg === "--write") {
        const outputPath = path.join(__dirname, "..", "programs", "vusd-vault", "src", "keys", "verifying_key.rs");
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, rust);
        console.error(`Verifying key exported to ${outputPath}`);
        return;
    }

    process.stdout.write(rust);
}

main();
